version: '3.2'
services:
  nginx_boids:
    build:
      context: .
    networks:
      - reverseproxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nginx_boids"
      - "traefik.frontend.rule=Host:boids.mwcm.ca"
      - "traefik.docker.network=reverseproxy_reverseproxy"

networks:
  reverseproxy:
    external:
      name: reverseproxy_reverseproxy
